# Generated by Django 5.1.1 on 2025-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disenador',
            name='cargo',
            field=models.CharField(choices=[('PROJECT MANAGER', 'Encargado de proyecto'), ('DISENADOR', 'Diseñador'), ('SUPERVISOR', 'Supervisor')], default='DISENADOR', max_length=20),
        ),
    ]
