# Generated by Django 5.1.1 on 2025-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_tarea_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disenador',
            name='cargo',
            field=models.CharField(choices=[('PROJECT MANAGER', 'Encargado de proyecto'), ('DISENADOR', 'Diseñador'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRADOR', 'Administrador')], default='DISENADOR', max_length=20),
        ),
    ]
