# Generated by Django 5.1.1 on 2025-03-10 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_disenador_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('disenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
