# Generated by Django 5.1.1 on 2025-03-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_disponibilidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
