# Generated by Django 5.1.1 on 2025-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_delete_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenador',
            name='disponibilidad',
            field=models.FloatField(default=40),
        ),
    ]
