# Generated by Django 5.1.6 on 2025-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_alter_notificacion_options_remove_notificacion_leida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
