# Generated by Django 5.1.6 on 2025-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_notificacion_leida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Tarea asignada'), ('TASK_STATUS_CHANGE', 'Cambio de estado de tarea'), ('TASK_REJECTED', 'Tarea rechazada'), ('TASK_COMPLETED', 'Tarea completada'), ('MENCION', 'Mención')], max_length=100),
        ),
    ]
